import Head from "next/head";
import Link from "next/link";
import {Treemap} from "@/components/TreeMap";
import {data, type Tree} from "@/data/data1";
import {testCases} from "@/data/testCases";
import React, { useState } from 'react';

export default function Home() {
    // State to keep track of the selected testCase
    const [selectedTestCase, setSelectedTestCase] = useState<Tree>(testCases[0]);

    // Function to handle button click and set the selected testCase
    const handleButtonClick = (testCase: Tree) => {
        setSelectedTestCase(testCase);
    };

    return (
        <>
            <Head>
                <title>Treemap Test</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
                <div className="flex gap-2 my-4">
                    {/* Buttons to select a testCase */}
                    {testCases.map((testCase, index) => (
                        <button
                            key={index}
                            onClick={() => handleButtonClick(testCase)}
                            className="rounded bg-white px-4 py-2 text-sm font-medium text-black shadow-sm hover:bg-gray-100"
                        >
                            {testCase.name}
                        </button>
                    ))}
                </div>
                <div className="container flex flex-col items-center justify-center gap-2 px-4">
                    <Treemap data={selectedTestCase} width={1600} height={900} />
                </div>
            </main>
        </>
    );
}
